// PSTN2 broadcast presentation player.
//
// A deck is three files next to its index.html:
//   narration.json        — scenes → narration segments (the script; captions show this text)
//   audio/manifest.json   — generated by tools/narrate/build-narration.mjs: per-scene MP3 + segment start times
//   scenes.js             — calls createDeck({ scenes: { <sceneId>: { build(s), cues: { <segmentId>: fn } } } })
//
// Narration drives the timeline: when a segment starts playing, its cue runs and the
// caption updates. With no pre-rendered audio, the player falls back to live speech
// (UK English voice ranking from the Law Enforcement deck), then to timed captions.
//
// URL options: #3 (start at scene 3) · ?autoplay=1 · ?kiosk=1 (loop forever, hide chrome)
//              ?capture=1 (QA: no audio, instant animations, window.__p2 automation hooks)

import { createSceneApi } from './pstn2-components.js';
import { icon } from './icons.js';
import { spoken } from './lexicon.js';
import { nextDeck } from './decks.js';

const params = new URLSearchParams(location.search);
const CAPTURE = params.has('capture');
const KIOSK = params.has('kiosk');
const AUTOPLAY = params.has('autoplay') || KIOSK;
const REDUCED = window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches;
const HOLD_AFTER_SCENE = 1400; // ms of quiet before moving to the next scene

const fmt = (sec) => `${Math.floor(sec / 60)}:${String(Math.floor(sec % 60)).padStart(2, '0')}`;
const store = {
    get(k, d) { try { const v = localStorage.getItem('p2:' + k); return v === null ? d : JSON.parse(v); } catch { return d; } },
    set(k, v) { try { localStorage.setItem('p2:' + k, JSON.stringify(v)); } catch { /* storage unavailable */ } },
};

// ---------------------------------------------------------------------------
// Live speech fallback (voice ranking from the Law Enforcement presentation)
// ---------------------------------------------------------------------------
let voices = [];
if ('speechSynthesis' in window) {
    voices = speechSynthesis.getVoices();
    speechSynthesis.onvoiceschanged = () => { voices = speechSynthesis.getVoices(); };
}
function ukVoice() {
    const v = voices.length ? voices : ('speechSynthesis' in window ? speechSynthesis.getVoices() : []);
    return v.find((x) => x.name.includes('Google') && x.lang === 'en-GB')
        || v.find((x) => x.name.includes('Neural') && x.lang === 'en-GB')
        || v.find((x) => x.name.startsWith('Daniel') && x.lang === 'en-GB')
        || v.find((x) => x.name.startsWith('Kate') && x.lang === 'en-GB')
        || v.find((x) => x.lang === 'en-GB')
        || v.find((x) => x.lang && x.lang.startsWith('en'));
}

// ---------------------------------------------------------------------------
export async function createDeck({ scenes: sceneDefs, narrationUrl = 'narration.json', manifestUrl = 'audio/manifest.json', deckId }) {
    const narration = await fetch(narrationUrl).then((r) => r.json());
    deckId = deckId || narration.deck;
    let manifest = null;
    if (!CAPTURE) {
        try {
            const r = await fetch(manifestUrl, { cache: 'no-cache' });
            if (r.ok) manifest = await r.json();
        } catch { /* no pre-rendered audio */ }
    }
    const phraseText = {};
    try {
        if (!narration.phrases && !manifest?.phrases) throw new Error('no phrases');
        const pr = await fetch('phrases.json');
        if (pr.ok) for (const ph of (await pr.json()).phrases) phraseText[ph.id] = ph.text;
    } catch { /* no phrases */ }
    const sceneList = narration.scenes.map((sc, i) => {
        const timing = manifest?.scenes?.[sc.id];
        // Estimate when there is no manifest: ~2.6 words/sec + pauses
        let t = 0.6;
        const segs = sc.segments.map((seg) => {
            const est = (seg.text.split(/\s+/).length / 2.6) + 0.35;
            const m = timing?.segments?.find((x) => x.id === seg.id);
            const out = { ...seg, start: m ? m.start : t, end: m ? m.end : t + est };
            t = out.end + 0.35;
            return out;
        });
        return { ...sc, index: i, segments: segs, audio: timing ? `audio/${timing.file}` : null, duration: timing ? timing.duration : t + 0.8 };
    });
    const total = sceneList.reduce((a, b) => a + b.duration, 0);

    // ---- DOM ----------------------------------------------------------------
    document.title = document.title || narration.title;
    const viewport = document.createElement('div');
    viewport.className = 'p2-viewport';
    viewport.innerHTML = `
      <div class="p2-stage ${narration.layout === 'wide' ? 'p2-wide' : ''}" role="region" aria-label="${narration.title}">
        <div class="p2-header">
          <div class="p2-kicker">${narration.kicker || 'PSTN2'}</div>
          <h1 class="p2-title" aria-live="polite"></h1>
          <div class="p2-counter"></div>
        </div>
        <div class="p2-content"></div>
        <div class="p2-caption-wrap"><div class="p2-caption" aria-live="polite"></div></div>
        <div class="p2-bug"><span>PSTN2</span> · pstn2.org</div>
        <div class="p2-overlay p2-start">
          <div class="p2-o-kicker">${narration.kicker || 'PSTN2 presentation'}</div>
          <h1>${narration.titleHtml || narration.title}</h1>
          <p>${narration.subtitle || ''}</p>
          <button class="p2-play-big" aria-label="Play presentation">${icon('play', { size: 76, stroke: 2.2, colour: '#fff' })}</button>
          <div class="p2-o-meta"><span>${sceneList.length} scenes · ${Math.max(1, Math.round(total / 60))} min</span><span><kbd>Space</kbd>play/pause</span><span><kbd>F</kbd>full screen</span><span><kbd>C</kbd>captions</span></div>
        </div>
        <div class="p2-overlay p2-end p2-hidden"></div>
      </div>
      <div class="p2-controls" role="toolbar" aria-label="Presentation controls">
        <div class="p2-progress"></div>
        <div class="p2-row">
          <a class="p2-home" href="../../index.html" title="All presentations">${icon('house', { size: 18 })}<span>PSTN2</span></a>
          <button class="p2-ctl" data-act="prev" title="Previous scene (←)">${icon('skip-back', { size: 20 })}</button>
          <button class="p2-ctl" data-act="play" title="Play / pause (Space)">${icon('play', { size: 22 })}</button>
          <button class="p2-ctl" data-act="next" title="Next scene (→)">${icon('skip-forward', { size: 20 })}</button>
          <span class="p2-ctl-label"></span>
          <span class="p2-spacer"></span>
          <button class="p2-ctl" data-act="chapters" title="Scenes">${icon('list-ordered', { size: 20 })}</button>
          <button class="p2-ctl p2-on" data-act="captions" title="Captions (C)">${icon('captions', { size: 20 })}</button>
          <button class="p2-ctl" data-act="mute" title="Mute (M)">${icon('volume-2', { size: 20 })}</button>
          <button class="p2-ctl" data-act="fullscreen" title="Full screen (F)">${icon('maximize', { size: 20 })}</button>
        </div>
      </div>
      <div class="p2-chapters" role="menu"></div>
      <div class="p2-toast"></div>`;
    document.body.append(viewport);
    const $ = (sel) => viewport.querySelector(sel);
    const stage = $('.p2-stage');
    const content = $('.p2-content');
    const titleEl = $('.p2-title');
    const counter = $('.p2-counter');
    const caption = $('.p2-caption');
    const startOverlay = $('.p2-start');
    const endOverlay = $('.p2-end');
    const progress = $('.p2-progress');
    const label = $('.p2-ctl-label');
    const chapters = $('.p2-chapters');
    const toastEl = $('.p2-toast');
    const playBtn = $('[data-act="play"]');
    const muteBtn = $('[data-act="mute"]');
    const capBtn = $('[data-act="captions"]');

    const fit = () => {
        const k = Math.min(window.innerWidth / 1920, window.innerHeight / 1080);
        stage.style.setProperty('--p2-scale', k);
    };
    fit();
    window.addEventListener('resize', fit);

    sceneList.forEach((sc, i) => {
        const seg = document.createElement('div');
        seg.className = 'p2-seg';
        seg.style.flexGrow = String(sc.duration);
        seg.title = `${i + 1}. ${sc.title}`;
        seg.innerHTML = '<i></i>';
        seg.addEventListener('click', () => go(i, { play: playing || !started }));
        progress.append(seg);
        const b = document.createElement('button');
        b.innerHTML = `<span>${i + 1}</span>${sc.title}`;
        b.addEventListener('click', () => { chapters.classList.remove('p2-open'); go(i, { play: true }); });
        chapters.append(b);
    });

    let captionsOn = store.get('captions', true);
    let muted = store.get('muted', false);
    const applyCaptions = () => { stage.classList.toggle('p2-captions-off', !captionsOn); capBtn.classList.toggle('p2-on', captionsOn); };
    const applyMute = () => { audio.muted = muted; muteBtn.innerHTML = icon(muted ? 'volume-x' : 'volume-2', { size: 20 }); };
    const toast = (msg) => { toastEl.textContent = msg; toastEl.classList.add('p2-show'); clearTimeout(toast.t); toast.t = setTimeout(() => toastEl.classList.remove('p2-show'), 1600); };

    // ---- timeline state ----------------------------------------------------
    const audio = new Audio();
    audio.preload = 'auto';
    applyCaptions();
    applyMute();
    let current = -1;
    let sceneEl = null;
    let api = null;
    let fired = new Set();
    let playing = false;
    let started = false;
    let clock = 0;            // seconds into the current scene (fallback modes)
    let lastTick = 0;
    let mode = 'audio';       // 'audio' | 'speech' | 'timer'
    let holdTimer = null;
    let speechQueue = [];
    let uid = 0;

    function cueFns(sc) {
        const def = sceneDefs[sc.id] || {};
        const cues = def.cues || {};
        const list = [];
        for (const [key, fn] of Object.entries(cues)) {
            const m = key.match(/^([^+]+)(?:\+([\d.]+))?$/);
            const seg = sc.segments.find((x) => x.id === m[1]);
            if (!seg) { console.warn(`[p2] cue "${key}" has no segment in scene ${sc.id}`); continue; }
            list.push({ key, at: seg.start + (m[2] ? parseFloat(m[2]) : 0), fn });
        }
        return list.sort((a, b) => a.at - b.at);
    }

    function buildScene(i) {
        const sc = sceneList[i];
        if (api) api.dispose();
        const old = sceneEl;
        if (old) { old.classList.add('p2-leaving'); setTimeout(() => old.remove(), CAPTURE ? 0 : 560); }
        sceneEl = document.createElement('div');
        sceneEl.className = 'p2-scene';
        sceneEl.dataset.uid = String(++uid);
        content.append(sceneEl);
        api = createSceneApi(sceneEl, { capture: CAPTURE, reducedMotion: REDUCED });
        api.phrase = phrase;
        api.setCaption = (text) => { caption.textContent = text || ''; };
        api.player = { pause: () => pause(true), get playing() { return playing; } };
        const def = sceneDefs[sc.id];
        if (!def) console.warn(`[p2] scene "${sc.id}" has no builder`);
        else if (def.build) def.build(api, sc);
        titleEl.classList.add('p2-leaving');
        setTimeout(() => { titleEl.textContent = sc.title; titleEl.classList.remove('p2-leaving'); }, CAPTURE ? 0 : 260);
        if (CAPTURE) titleEl.textContent = sc.title;
        counter.innerHTML = `<b>${String(i + 1).padStart(2, '0')}</b> / ${String(sceneList.length).padStart(2, '0')}`;
        fired = new Set();
        sc.cueList = cueFns(sc);
        caption.textContent = '';
        [...progress.children].forEach((seg, j) => { seg.classList.toggle('p2-done', j < i); seg.querySelector('i').style.width = j < i ? '100%' : '0'; });
        [...chapters.children].forEach((b, j) => b.classList.toggle('p2-current', j === i));
        label.innerHTML = `<b>${i + 1}. ${sc.title}</b>`;
        history.replaceState(null, '', `${location.pathname}${location.search}#${i + 1}`);
    }

    // Short pre-rendered voice lines for interactive scenes (phrases.json → audio/phrases/<id>.mp3)
    const phraseAudio = new Audio();
    function phrase(id, { text } = {}) {
        const line = text || phraseText[id] || '';
        caption.textContent = line;
        caption.classList.toggle('p2-long', line.length > 165);
        if (CAPTURE || muted) return Promise.resolve();
        const file = manifest?.phrases?.[id];
        return new Promise((resolve) => {
            if (file) {
                phraseAudio.src = `audio/${file}`;
                phraseAudio.onended = resolve;
                phraseAudio.onerror = resolve;
                phraseAudio.play().catch(resolve);
            } else if ('speechSynthesis' in window && line) {
                speechSynthesis.cancel();
                const u = new SpeechSynthesisUtterance(spoken(line));
                const v = ukVoice(); if (v) u.voice = v;
                u.lang = 'en-GB'; u.rate = 1;
                u.onend = resolve; u.onerror = resolve;
                speechSynthesis.speak(u);
            } else resolve();
        });
    }

    function fireDue(t) {
        const sc = sceneList[current];
        for (const c of sc.cueList) {
            if (c.at <= t + 0.02 && !fired.has(c.key)) {
                fired.add(c.key);
                try { c.fn(api, sc); } catch (e) { console.error(`[p2] cue ${sc.id}/${c.key}`, e); }
            }
        }
        let seg = null;
        for (const x of sc.segments) if (x.start <= t + 0.02) seg = x;
        const text = seg && t <= seg.end + 0.6 ? seg.text : (seg && t > seg.end + 0.6 ? '' : '');
        if (caption.textContent !== text) { caption.textContent = text; caption.classList.toggle('p2-long', text.length > 165); }
        const bar = progress.children[current]?.querySelector('i');
        if (bar) bar.style.width = `${Math.min(100, (t / sc.duration) * 100)}%`;
    }

    function stopMedia() {
        audio.pause();
        if ('speechSynthesis' in window) speechSynthesis.cancel();
        speechQueue = [];
        clearTimeout(holdTimer);
    }

    function go(i, { play = playing } = {}) {
        if (i < 0 || i >= sceneList.length) return;
        stopMedia();
        endOverlay.classList.add('p2-hidden');
        current = i;
        clock = 0;
        buildScene(i);
        const sc = sceneList[i];
        mode = sc.audio ? 'audio' : ('speechSynthesis' in window && !CAPTURE ? 'speech' : 'timer');
        if (mode === 'audio') { audio.src = sc.audio; audio.currentTime = 0; }
        fireDue(0);
        if (play) start(); else pause(true);
    }

    function start() {
        started = true;
        playing = true;
        startOverlay.classList.add('p2-hidden');
        playBtn.innerHTML = icon('pause', { size: 22 });
        const sc = sceneList[current];
        if (mode === 'audio') {
            audio.play().catch(() => { mode = 'speech' in window ? 'timer' : 'timer'; switchToFallback(); });
        } else if (mode === 'speech') {
            if (speechSynthesis.paused && speechQueue.length) speechSynthesis.resume(); else speakFrom(sc, clock);
        }
        lastTick = performance.now();
        requestAnimationFrame(loop);
    }

    function pause(silent = false) {
        playing = false;
        playBtn.innerHTML = icon('play', { size: 22 });
        if (mode === 'audio') audio.pause();
        if (mode === 'speech' && 'speechSynthesis' in window) speechSynthesis.pause();
        clearTimeout(holdTimer);
        if (!silent) viewport.classList.remove('p2-idle');
    }

    function switchToFallback() {
        mode = 'speechSynthesis' in window ? 'speech' : 'timer';
        clock = audio.currentTime || 0;
        if (mode === 'speech') speakFrom(sceneList[current], clock);
    }

    // Live speech: speak segments in order; each utterance start moves the clock
    function speakFrom(sc, t) {
        speechSynthesis.cancel();
        const pending = sc.segments.filter((seg) => seg.end > t);
        speechQueue = pending;
        const sid = current;
        const voice = ukVoice();
        const next = () => {
            if (sid !== current || !playing) return;
            const seg = speechQueue.shift();
            if (!seg) { clock = sc.duration; return sceneEnded(); }
            const u = new SpeechSynthesisUtterance(spoken(seg.say || seg.text));
            u.rate = 0.95; u.pitch = 1; u.lang = 'en-GB';
            if (voice) u.voice = voice;
            u.onstart = () => { clock = Math.max(clock, seg.start); };
            u.onend = () => { clock = Math.max(clock, seg.end); setTimeout(next, 250); };
            u.onerror = (e) => { if (e.error === 'interrupted' || e.error === 'canceled') return; mode = 'timer'; };
            speechSynthesis.speak(u);
        };
        next();
    }

    function loop(now) {
        if (!playing) return;
        const dt = (now - lastTick) / 1000;
        lastTick = now;
        let t;
        if (mode === 'audio') t = audio.currentTime;
        else if (mode === 'timer') { clock += dt; t = clock; if (t >= sceneList[current].duration) { sceneEnded(); return; } }
        else t = clock;
        fireDue(t);
        requestAnimationFrame(loop);
    }

    function sceneEnded() {
        if (!playing) return;
        fireDue(9999);
        clearTimeout(holdTimer);
        if (sceneDefs[sceneList[current].id]?.interactive) { pause(true); return; }
        holdTimer = setTimeout(() => {
            if (!playing) return;
            if (current < sceneList.length - 1) go(current + 1, { play: true });
            else if (KIOSK) go(0, { play: true });
            else showEnd();
        }, HOLD_AFTER_SCENE);
    }
    audio.addEventListener('ended', sceneEnded);
    audio.addEventListener('error', () => { if (mode === 'audio' && audio.src) { console.warn('[p2] audio failed, using live speech'); switchToFallback(); } });

    function showEnd() {
        pause(true);
        caption.textContent = '';
        const nd = nextDeck(deckId);
        endOverlay.innerHTML = `
          <div class="p2-o-kicker">End of presentation</div>
          <h1>${narration.title}</h1>
          <p>${narration.endNote || 'Thank you for watching.'}</p>
          <div class="p2-end-actions">
            <button class="p2-btn-lg" data-act="replay">${icon('rotate-ccw', { size: 30 })}Watch again</button>
            ${nd ? `<a class="p2-btn-lg p2-primary" href="../${nd.id}/index.html"><span><span class="p2-next-title">Up next</span>${nd.title}</span>${icon('arrow-right', { size: 30 })}</a>` : ''}
            <a class="p2-btn-lg" href="../../index.html">${icon('house', { size: 30 })}All presentations</a>
          </div>`;
        endOverlay.querySelector('[data-act="replay"]').addEventListener('click', () => go(0, { play: true }));
        endOverlay.classList.remove('p2-hidden');
        [...progress.children].forEach((seg) => seg.classList.add('p2-done'));
    }

    // ---- input -------------------------------------------------------------
    const toggle = () => { if (playing) pause(); else start(); };
    const fullscreen = () => {
        if (document.fullscreenElement) document.exitFullscreen?.();
        else (document.documentElement.requestFullscreen || document.documentElement.webkitRequestFullscreen)?.call(document.documentElement);
    };
    viewport.addEventListener('click', (e) => {
        const btn = e.target.closest('[data-act]');
        if (!btn) {
            if (e.target.closest('.p2-play-big')) return;
            if (e.target.closest('.p2-stage') && !e.target.closest('.p2-overlay') && !e.target.closest('a,button,input,select,textarea,label,[data-interactive]')) toggle();
            return;
        }
        const act = btn.dataset.act;
        if (act === 'play') toggle();
        if (act === 'prev') go(Math.max(0, current - 1), { play: playing });
        if (act === 'next') go(Math.min(sceneList.length - 1, current + 1), { play: playing });
        if (act === 'chapters') chapters.classList.toggle('p2-open');
        if (act === 'captions') { captionsOn = !captionsOn; store.set('captions', captionsOn); applyCaptions(); toast(captionsOn ? 'Captions on' : 'Captions off'); }
        if (act === 'mute') { muted = !muted; store.set('muted', muted); applyMute(); toast(muted ? 'Muted' : 'Sound on'); }
        if (act === 'fullscreen') fullscreen();
    });
    $('.p2-play-big').addEventListener('click', (e) => { e.stopPropagation(); start(); });
    document.addEventListener('keydown', (e) => {
        if (e.metaKey || e.ctrlKey || e.altKey) return;
        if (e.target.closest && e.target.closest('input,select,textarea,[contenteditable]')) return;
        const k = e.key;
        if (k === ' ' || k === 'k' || k === 'K') { e.preventDefault(); toggle(); }
        else if (k === 'ArrowRight' || k === 'PageDown') { e.preventDefault(); go(Math.min(sceneList.length - 1, current + 1), { play: playing || !started }); }
        else if (k === 'ArrowLeft' || k === 'PageUp') { e.preventDefault(); go(Math.max(0, current - 1), { play: playing || !started }); }
        else if (k === 'Home') go(0, { play: playing });
        else if (k === 'End') go(sceneList.length - 1, { play: playing });
        else if (k === 'f' || k === 'F') fullscreen();
        else if (k === 'c' || k === 'C') capBtn.click();
        else if (k === 'm' || k === 'M') muteBtn.click();
        else if (/^[1-9]$/.test(k)) go(Math.min(sceneList.length - 1, Number(k) - 1), { play: playing || !started });
        else if (k === 'Escape') chapters.classList.remove('p2-open');
        viewport.classList.remove('p2-idle');
    });
    let idle;
    const wake = () => {
        viewport.classList.remove('p2-idle');
        clearTimeout(idle);
        idle = setTimeout(() => { if (playing) viewport.classList.add('p2-idle'); }, KIOSK ? 600 : 2600);
    };
    document.addEventListener('mousemove', wake);
    document.addEventListener('touchstart', wake, { passive: true });

    // ---- start -------------------------------------------------------------
    const initial = Math.min(sceneList.length - 1, Math.max(0, (parseInt(location.hash.slice(1), 10) || 1) - 1));
    if (document.fonts?.ready) await document.fonts.ready;
    go(initial, { play: false });
    if (KIOSK) viewport.classList.add('p2-idle');
    if (AUTOPLAY && !CAPTURE) start();

    // QA hooks: build any scene and run its cues up to a segment, instantly.
    if (CAPTURE) {
        startOverlay.classList.add('p2-hidden');
        document.documentElement.classList.add('p2-capture');
        window.__p2 = {
            scenes: sceneList.map((sc) => ({ id: sc.id, title: sc.title, segments: sc.segments.map((x) => x.id) })),
            async show(i, upTo = 'all') {
                go(i, { play: false });
                const sc = sceneList[i];
                const limit = upTo === 'all' ? Infinity : sc.segments[upTo].start + 0.01;
                for (const c of sc.cueList) {
                    if (c.at > limit) break;
                    if (!fired.has(c.key)) { fired.add(c.key); await c.fn(api, sc); }
                }
                const seg = [...sc.segments].reverse().find((x) => x.start <= limit) || sc.segments[0];
                caption.textContent = seg ? seg.text : '';
                caption.classList.toggle('p2-long', caption.textContent.length > 165);
                await new Promise((r) => setTimeout(r, 60)); // not rAF: frames pause in background tabs
                return { scene: sc.id, title: sc.title };
            },
            end() { showEnd(); },
        };
        window.dispatchEvent(new Event('p2-ready'));
    }
    return { go, start, pause, scenes: sceneList };
}
